# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.94.0"

generated_fastfile_id "678402ec-d564-47e6-a1ed-b6530fee19ad"

default_platform(:ios)

 before_all do |lane,options|
  clear_derived_data
   ENV["FASTLANE_EXPLICIT_OPEN_SIMULATOR"] = "2"  
  end

platform :ios do
  desc "Description of what the lane does"
      appId = "com.krungsri.fizbuz"
      username = "itaycap.digital@krungsri.com"
      scheme = "FizzBuzz"
      configuration = "ad-hoc"
      #token = "68c18894f9ca4a3ad7c733257ffe5889825ce24f" #for uchoose
      # secretKey = "7c863c56add739ecce170c8ee5072c94edccfeb50d19f9ef88211efdbe12f1fe" #for uchoose
      token = "fecc2f93b1164f5217c9ff03d0ee37dac34aa913" #for FizzBuzz
      secretKey = "b9f8b831d8deb92b855e648965f59a4f94be257746dcc039f230b60987768b74" #for FizzBuzz


desc "Push a new beta build to Fabric beta"
  lane :fabric do
      
      sigh(
      username: username,
      app_identifier: appId,
      adhoc: true
    )

    	 build_ios_app(
      workspace: "FizzBuzz.xcworkspace",
      configuration: "Debug",
      clean: false,
      scheme: scheme, 
      export_method: configuration,
  )

    commit_message = last_git_commit[:message]

    # this will generate the changelog based on your last commits
    changelog_from_git_commits

    crashlytics(
      api_token: token,
      build_secret: secretKey,
      # emails: "pumwaree@gmail.com",
      notifications: true
    )
  end

  
lane :tests do
  run_tests(workspace: "FizzBuzz.xcworkspace",
     devices: ["iPhone 8"],
     scheme: "FizzBuzz",
     skip_testing: "FizzBuzzUITests"
            )
end


lane :make_ipa do
  # increment_version_number(
  #    # bump_type: "major, minor, patch"
  # # build_number: "3.0"
  # bump_type: "patch"
  # )

  # increment_build_number(
  # build_number: "1.0.1"
  #   )  
    gym(
      workspace: "FizzBuzz.xcworkspace",
      configuration: "Debug",
      scheme: "FizzBuzz",
      clean: true,
      include_bitcode: false,
      output_directory: "./build",
      output_name: "FizzBuzzTest_",
      export_method: "development"

      # workspace: "FizzBuzz.xcworkspace",
      # configuration: "Release",
      # scheme: "FizzBuzz",
      # clean: true,
      # include_bitcode: false,
      # output_directory: "./build",
      # output_name: "FizzBuzzTestFlight",
      # export_method: "app-store"
    )

  end

  lane :beta do
  pilot(ipa: "./build/FizzBuzzTest_.ipa",
    apple_id: "com.krungsri.fizbuz"
    )

end

  lane :uploadTestFlight do
    build_number = latest_testflight_build_number(
      app_identifier: CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier),
      version: get_version_number(xcodeproj: "FizzBuzz")
    ) + 1

    increment_build_number({
      build_number: build_number
    })
    pilot(
    username: "itaycap.digital@krungsri.com",
    app_identifier: "com.krungsri.fizbuz",
    ipa: "./build/FizzBuzzTestFlight.ipa",
    apple_id: "com.krungsri.fizbuz",
    skip_waiting_for_build_processing: true
)
  end


end
